Backups:
  FirstServer:
    Active: True
    Priority: High
    Log: True
    Files:
      BungeeCord:
        Type: Dir File
        Source: /home/bungee/
        Destination: /home/bungee/backups/
        Compress: True
      Lobby:
        Type: Dir File
        Source: /home/lobby/
        Destination: /home/lobby/backups/
        Compress: True
    Settings:
      Destination_Type: FTP
      FTP:
        Host:
        Port:
        Username:
        Password:
      Every:
        Seconds: 0
        Minutes: 0
        Hours: 0
        Days: 1
  SecondServer:
    Active: True
    Priority: Medium
    Log: True
    Files:
      BungeeCord:
        Type: Dir File
        Source: /home/bungee/
        Destination: /home/bungee/backups/
        Compress: True
      Lobby:
        Type: Dir File
        Source: /home/lobby/
        Destination: /home/lobby/backups/
        Compress: True
    Settings:
      Destination_Type: Local
      FTP:
        Host:
        Port:
        Username:
        Password:
      Every:
        Seconds: 0
        Minutes: 0
        Hours: 3
        Days: 0
Program_Settings:
  Script_Dir: /home/scripts/
  Max_Backups: 3
  Debug_Level: 2
  Version: 0.1
