###################################################
#	DSMM v0.8 - Dedicaded Server Minecraft Manager  #
#	Author: Fabrimat                                #
#	Repository: https://github.com/Fabrimat/DSMM    #
###################################################
#
# To add more server copy and paste the first server below.
#
Servers:
  # Here are some templates.
  # The name you will use in the program
  Bungeecord:
    # The name of the screen
    Name: Bungee
    # The RAM in Java format
    Ram: 512M
    # The file.jar to execute
    File_Name: BungeeCord.jar
    # The directory where is located the file.jar
    Directory: /home/server/bungee
    # The command that is needed to stop the server
    Stop_Command: end
    # The description, write what you want
    Description: 'The BungeeCord Network'
    # The ip from where accepts connections
    Server_Ip: 0.0.0.0
    # Actually non working
    Port: 25565
  Lobby:
    ID: 1
    MinRAM: 2048M
    MaxRAM: 2048M
    File_Name: spigot.jar
    Directory: /home/server/lobby
    StopCommands:
        - save-all
        - stop
    Description: 'The default connection server'
    Server_Ip: 0.0.0.0
    Port: 25566
ProgramSettings:
  CheckRunningTime: 60
  Version: 0.8 #Do not change it!
