###################################################
#	DSMM v2.0 - Dedicaded Server Minecraft Manager  #
#	Author: Fabrimat                                #
#	Repository: https://github.com/Fabrimat/DSMM    #
###################################################
#
# To add more server copy and paste the first server below.
#
Servers:
  # Here are some templates.
  # The name you will use in the program
  Bungeecord:
    ID: 1
    MinRAM: 256M
    MaxRAM: 512M
    FileName: bungeecord.jar
    Directory: /home/server/bungeecord
    StopCommands:
        - end
    Description: 'The Bungeecord Proxy'
    IP: 0.0.0.0
    Port: 25565
  Lobby:
    ID: 2
    MinRAM: 2048M
    MaxRAM: 2048M
    FileName: spigot.jar
    Directory: /home/server/lobby
    StopCommands:
        - save-all
        - stop
    Description: 'The default connection server'
    IP: 0.0.0.0
    Port: 25566
ProgramSettings:
  CheckRunningTime: 60
  Version: 2.0 #Do not change it!
